auth0:
  audience: http://localhost:4200

spring:
  application:
    name: gateway-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-vq2nkixrb8245ghu.us.auth0.com
  cloud:
    gateway:
      routes:
        - id: compte-id
          uri: lb://ms-comptes
          predicates:
            - Path=/comptes/**
          filters:
            - AddRequestHeader=first-request, first-request-header
            - AddResponseHeader=first-response, first-response-header
        - id: facturation-id
          uri: lb://ms-facturations
          predicates:
            - Path=/facturations/**
          filters:
            - AddRequestHeader=first-request, first-request-header
            - AddResponseHeader=first-response, first-response-header
        - id: commandes-id
          uri: lb://ms-commandes
          predicates:
            - Path=/commandes/**
          filters:
            - AddRequestHeader=first-request, first-request-header
            - AddResponseHeader=first-response, first-response-header
        - id: composants-id
          uri: lb://ms-composants
          predicates:
            - Path=/composants/**
          filters:
            - AddRequestHeader=first-request, first-request-header
            - AddResponseHeader=first-response, first-response-header
        # ajouter les éventuels services suivants
server:
  port: 8080